package com.kosherclimate.userapp.models

data class CropInfoModel(
    val farmer_id: String,
    val farmer_uniqueId: String,
    val plot_no: String,
    val nursery: String,
    val dt_ploughing: String,
    val dt_transplanting: String,
    val area_in_acers: String,
    val farmer_plot_uniqueid: String,
    val crop_season_lastyrs: String,
    val crop_season_currentyrs: String,
    val crop_variety_lastyrs: String,
    val crop_variety_currentyrs: String,
    val yeild_lastyrs: String,
    val fertilizer_1_name: String,
    val fertilizer_1_lastyrs: String,
    val fertilizer_1_currentyrs: String,
    val fertilizer_2_name: String,
    val fertilizer_2_lastyrs: String,
    val fertilizer_2_currentyrs: String,
    val fertilizer_3_name: String,
    val fertilizer_3_lastyrs: String,
    val fertilizer_3_currentyrs: String,
    val area_acre_awd: String,
    val area_other_awd: String,
    val patta_number: String,
    val daag_number: String,
    val khatha_number: String,
    val pattadhar_number: String,
    val khatian_number: String,
    val organization_id: String,
    val gender: String,
    val area_in_other: String,
)
